# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sto', models.CharField(blank=True, max_length=96, null=True)),
                ('cislo', models.CharField(blank=True, max_length=10, null=True)),
                ('firma', models.CharField(blank=True, max_length=30, null=True)),
                ('typ', models.CharField(blank=True, max_length=25, null=True)),
                ('meridlo', models.CharField(blank=True, max_length=43, null=True)),
                ('sn', models.CharField(blank=True, max_length=9, null=True)),
                ('datum', models.DateTimeField(blank=True, null=True)),
                ('stav', models.CharField(blank=True, max_length=11, null=True)),
                ('jednotka', models.CharField(blank=True, max_length=3, null=True)),
                ('posledni_odecet', models.CharField(blank=True, db_column='posledni odecet', max_length=19, null=True)),
                ('posledni_stav', models.CharField(blank=True, db_column='posledni stav', max_length=10, null=True)),
                ('jednotka_2', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'db_table': 'daily',
                'managed': False,
            },
        ),
    ]
